question 4 - least squares

In [94]:
import numpy as np
b = np.array([6,1,5,2])
A = np.array([[2,1,2],[1,-2,1],[1,2,3],[1,1,1]])
ATA = A.transpose()@A
L = np.linalg.cholesky(ATA)
L


array([[2.64575131, 0.        , 0.        ],
       [1.13389342, 2.9519969 , 0.        ],
       [3.40168026, 1.06465462, 1.51495279]])

In [95]:
def forward_sub(L,b):
    L = np.copy(L)
    b = np.copy(b)
    for i in range(len(L)):
        b[i] = b[i] / L[i,i]
        L[i][i] = 1
        for j in range(i+1,len(L)):
            b[j] = b[j] - b[i] * (L[j][i])
            L[j] = L[j] - L[i] * (L[j][i])
    return b


In [96]:
def backward_sub(LT,y):
    LT = np.copy(LT)
    y = np.copy(y)
    for i in reversed(range(len(L))):
        y[i] = y[i] / LT[i,i]
        LT[i][i] = 1
        for j in range(0,i):
            y[j] = y[j] - y[i] * (LT[j][i])
            LT[j] = LT[j] - LT[i] * (LT[j][i])
    return y

In [97]:
ATB = A.transpose() @ b
y = forward_sub(L,ATB)
x = backward_sub(L.transpose(),y)
print(ATA @ x - ATB)
print(A@x -b)

#just an example
C = np.array([[2,1,1],[0,2,1],[0,0,2]])
d = np.array([8,8,8])
print(backward_sub(C,d))





[ -6 -10 -12]
[-2  1 -3  0]
[1 2 4]
